import {
    LayoutDashboard,
    ShieldCheck,
    UserRoundCog,
    Receipt,
    CreditCard,
    BarChart3,
    Store,
    Warehouse,
    Users,
    Tag,
    Layers,
    Package,
    Boxes,
    FileText,
    Banknote,
    Search,
    Mail,
    Phone,
    Calendar,
    CornerUpLeft,
    Building2,
    Eye,
    Plus,
    Trash2,
    Edit,
    AlertTriangle,
    RefreshCw,
    CheckCircle,
    XCircle,
    Lock,
    Power,
    ChevronDown,
    MoreVertical,
    Check,
    X,
    Info,
    AlertCircle,
    Settings,
    LogOut,
    User,
    ArrowLeft,
    ArrowRight,
    Download,
    Upload,
    Filter,
    FileSpreadsheet,
    FileImage,
    HelpCircle,
    Bell,
    Globe,
    MapPin,
    Smartphone,
    MailOpen,
    Clock,
    IndianRupee,
    ShoppingCart,
    ShoppingBag,
    Archive,
    Grid,
    List,
    Maximize2,
    Minimize2,
    Menu,
    Percent,
    PieChart,
    ArrowUpCircle,
    ArrowDownCircle,
    Zap,
    ChevronUp,
    ChevronsUpDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    Activity,
    Truck,
    TrendingDown,
    TrendingUp,
    Printer,
    X as CloseIcon
} from 'lucide-react';


import {
    FiPlus,
    FiGrid,
    FiEdit,
    FiTrash2,
    FiEye,
    FiSettings,
    FiLogOut,
    FiUser,
    FiSearch,
    FiFilter,
    FiDownload,
    FiUpload,
    FiMoreVertical,
    FiChevronDown,
    FiCheck,
    FiX,
    FiAlertCircle,
    FiInfo,
    FiDatabase,
    FiHome,
    FiLayers,
    FiPackage,
    FiTag,
    FiUsers,
    FiBarChart2,
    FiCreditCard,
    FiFileText,
    FiPercent
} from 'react-icons/fi';

// Lucide Icons
export const Icons = {
    Dashboard: LayoutDashboard,
    Roles: ShieldCheck,
    Admin: UserRoundCog,
    Tax: Receipt,
    Payment: CreditCard,
    Report: BarChart3,
    Store: Store,
    Warehouse: Warehouse,
    Employee: Users,
    Discount: Tag,
    Category: Layers,
    Product: Package,
    Stock: Boxes,
    Invoice: FileText,
    PaymentMethod: Banknote,
    Search: Search,
    Mail: Mail,
    Phone: Phone,
    Calendar: Calendar,
    Building: Building2,
    View: Eye,
    Add: Plus,
    Plus: Plus,
    Delete: Trash2,
    Edit: Edit,
    Warning: AlertTriangle,
    Reset: RefreshCw,
    Success: CheckCircle,
    Error: XCircle,
    Lock: Lock,
    Status: Power,
    Dropdown: ChevronDown,
    Actions: MoreVertical,
    Check: Check,
    X: X,
    Close: X,
    Info: Info,
    Alert: AlertCircle,
    Settings: Settings,
    Logout: LogOut,
    LogOut: LogOut,
    User: User,
    Back: ArrowLeft,
    Forward: ArrowRight,
    Download: Download,
    Upload: Upload,
    Filter: Filter,
    Excel: FileSpreadsheet,
    Image: FileImage,
    Help: HelpCircle,
    Notification: Bell,
    Bell: Bell,
    Website: Globe,
    Location: MapPin,
    Mobile: Smartphone,
    MailOpen: MailOpen,
    Time: Clock,
    Currency: IndianRupee,
    DollarSign: IndianRupee,
    Cart: ShoppingCart,
    Bag: ShoppingBag,
    Archive: Archive,
    Grid: Grid,
    List: List,
    Expand: Maximize2,
    Shrink: Minimize2,
    Menu: Menu,
    CreditCard: CreditCard,
    CloseIcon: CloseIcon,
    Shield: ShieldCheck,
    Users: Users,
    Receipt: Receipt,
    BarChart: BarChart3,
    Tag: Tag,
    Layers: Layers,
    Package: Package,
    Boxes: Boxes,
    FileText: FileText,
    Percent: Percent,
    Trash: Trash2,
    XCircle: XCircle,
    CheckCircle: CheckCircle,
    AlertTriangle: AlertTriangle,
    ChevronUp: ChevronUp,
    ChevronDown: ChevronDown,
    Sort: ChevronsUpDown,
    SortUp: ChevronUp,
    SortDown: ChevronDown,
    CornerUpLeft: CornerUpLeft,
    Refresh: RefreshCw,
    RefreshCw: RefreshCw,
    PieChart: PieChart,
    ArrowUpCircle: ArrowUpCircle,
    ArrowDownCircle: ArrowDownCircle,
    Zap: Zap,
    Clock: Clock,
    ChevronLeft: ChevronLeft,
    ChevronRight: ChevronRight,
    ChevronsLeft: ChevronsLeft,
    ChevronsRight: ChevronsRight,
    Activity: Activity,
    Truck: Truck,
    TrendingDown: TrendingDown,
    TrendingUp: TrendingUp,
    AlertCircle: AlertCircle,
    Banknote: Banknote,
    Smartphone: Smartphone,
    ShoppingCart: ShoppingCart,
    UserRoundCog: UserRoundCog,
    Printer: Printer
};


// React Icons (Fi)
export const FiIcons = {
    Plus: FiPlus,
    Grid: FiGrid,
    Edit: FiEdit,
    Delete: FiTrash2,
    View: FiEye,
    Settings: FiSettings,
    Logout: FiLogOut,
    User: FiUser,
    Search: FiSearch,
    Filter: FiFilter,
    Download: FiDownload,
    Upload: FiUpload,
    Actions: FiMoreVertical,
    Dropdown: FiChevronDown,
    Check: FiCheck,
    Close: FiX,
    Alert: FiAlertCircle,
    Info: FiInfo,
    Database: FiDatabase,
    Home: FiHome,
    Layers: FiLayers,
    Package: FiPackage,
    Tag: FiTag,
    Users: FiUsers,
    Chart: FiBarChart2,
    Card: FiCreditCard,
    File: FiFileText,
    Percent: FiPercent
};

export default Icons;
